apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-deploy
  name: app-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-deploy
  strategy: {}
  template:
    metadata:
      labels:
        app: app-deploy
    spec:
      containers:
      - image: test:latest
        imagePullPolicy: IfNotPresent
        name: test
        env:
          - name: NAME
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: NAME
